name: Java CI

on: [push]

jobs:

  build_faiss:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@master
      with:
        submodules: true
    - uses: whoan/docker-build-with-cache-action@v5
      with:
        username: victor-paltz
        password: "${{ secrets.GITHUB_TOKEN }}"
        registry: docker.pkg.github.com
        #or
        #registry: ghcr.io
        image_name: JFaiss-CPU
        dockerfile: ../../Dockerfile

    # - name: Debugging with tmate
    #   uses: mxschmitt/action-tmate@v3
    
    - uses: actions/upload-artifact@v2
      with:
        name: faiss_JNI_and_SO
        path: build
    

  build:
    needs: build_faiss
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: faiss_JNI_and_SO
          path: build_copy
      - name: Move
        run: |
          rm -rf src/main/java/com/vectorsearch/faiss/swig
          cp -r build_copy/java/com/vectorsearch/faiss/swig src/main/java/com/vectorsearch/faiss/swig
          rm -rf src/main/resources
          cp -r build_copy/resources src/main/resources

      - name: Publish package
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}